services:
  selenium-swag-labs:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - .:/app
      - m2:/root/.m2
    networks:
      - swag-labs-test

volumes:
  m2:
  modules:

networks:
  swag-labs-test:
    driver: bridge